// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.example.grpc;

public final class TaskMessage {
  private TaskMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:task.TaskRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 路径前缀
     * </pre>
     *
     * <code>string pathPrefix = 1;</code>
     * @return The pathPrefix.
     */
    java.lang.String getPathPrefix();
    /**
     * <pre>
     * 路径前缀
     * </pre>
     *
     * <code>string pathPrefix = 1;</code>
     * @return The bytes for pathPrefix.
     */
    com.google.protobuf.ByteString
        getPathPrefixBytes();

    /**
     * <pre>
     * 路径后缀
     * </pre>
     *
     * <code>string pathSuffix = 2;</code>
     * @return The pathSuffix.
     */
    java.lang.String getPathSuffix();
    /**
     * <pre>
     * 路径后缀
     * </pre>
     *
     * <code>string pathSuffix = 2;</code>
     * @return The bytes for pathSuffix.
     */
    com.google.protobuf.ByteString
        getPathSuffixBytes();

    /**
     * <pre>
     * 需要处理的最大编号
     * </pre>
     *
     * <code>int32 maxNumber = 3;</code>
     * @return The maxNumber.
     */
    int getMaxNumber();
  }
  /**
   * Protobuf type {@code task.TaskRequest}
   */
  public static final class TaskRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:task.TaskRequest)
      TaskRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskRequest.newBuilder() to construct.
    private TaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskRequest() {
      pathPrefix_ = "";
      pathSuffix_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pathPrefix_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pathSuffix_ = s;
              break;
            }
            case 24: {

              maxNumber_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.TaskMessage.TaskRequest.class, com.example.grpc.TaskMessage.TaskRequest.Builder.class);
    }

    public static final int PATHPREFIX_FIELD_NUMBER = 1;
    private volatile java.lang.Object pathPrefix_;
    /**
     * <pre>
     * 路径前缀
     * </pre>
     *
     * <code>string pathPrefix = 1;</code>
     * @return The pathPrefix.
     */
    @java.lang.Override
    public java.lang.String getPathPrefix() {
      java.lang.Object ref = pathPrefix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathPrefix_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 路径前缀
     * </pre>
     *
     * <code>string pathPrefix = 1;</code>
     * @return The bytes for pathPrefix.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathPrefixBytes() {
      java.lang.Object ref = pathPrefix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATHSUFFIX_FIELD_NUMBER = 2;
    private volatile java.lang.Object pathSuffix_;
    /**
     * <pre>
     * 路径后缀
     * </pre>
     *
     * <code>string pathSuffix = 2;</code>
     * @return The pathSuffix.
     */
    @java.lang.Override
    public java.lang.String getPathSuffix() {
      java.lang.Object ref = pathSuffix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathSuffix_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 路径后缀
     * </pre>
     *
     * <code>string pathSuffix = 2;</code>
     * @return The bytes for pathSuffix.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathSuffixBytes() {
      java.lang.Object ref = pathSuffix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathSuffix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAXNUMBER_FIELD_NUMBER = 3;
    private int maxNumber_;
    /**
     * <pre>
     * 需要处理的最大编号
     * </pre>
     *
     * <code>int32 maxNumber = 3;</code>
     * @return The maxNumber.
     */
    @java.lang.Override
    public int getMaxNumber() {
      return maxNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPathPrefixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pathPrefix_);
      }
      if (!getPathSuffixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pathSuffix_);
      }
      if (maxNumber_ != 0) {
        output.writeInt32(3, maxNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPathPrefixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pathPrefix_);
      }
      if (!getPathSuffixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pathSuffix_);
      }
      if (maxNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.TaskMessage.TaskRequest)) {
        return super.equals(obj);
      }
      com.example.grpc.TaskMessage.TaskRequest other = (com.example.grpc.TaskMessage.TaskRequest) obj;

      if (!getPathPrefix()
          .equals(other.getPathPrefix())) return false;
      if (!getPathSuffix()
          .equals(other.getPathSuffix())) return false;
      if (getMaxNumber()
          != other.getMaxNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATHPREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPathPrefix().hashCode();
      hash = (37 * hash) + PATHSUFFIX_FIELD_NUMBER;
      hash = (53 * hash) + getPathSuffix().hashCode();
      hash = (37 * hash) + MAXNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMaxNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.TaskMessage.TaskRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code task.TaskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:task.TaskRequest)
        com.example.grpc.TaskMessage.TaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.TaskMessage.TaskRequest.class, com.example.grpc.TaskMessage.TaskRequest.Builder.class);
      }

      // Construct using com.example.grpc.TaskMessage.TaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pathPrefix_ = "";

        pathSuffix_ = "";

        maxNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskRequest_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskRequest getDefaultInstanceForType() {
        return com.example.grpc.TaskMessage.TaskRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskRequest build() {
        com.example.grpc.TaskMessage.TaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskRequest buildPartial() {
        com.example.grpc.TaskMessage.TaskRequest result = new com.example.grpc.TaskMessage.TaskRequest(this);
        result.pathPrefix_ = pathPrefix_;
        result.pathSuffix_ = pathSuffix_;
        result.maxNumber_ = maxNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.TaskMessage.TaskRequest) {
          return mergeFrom((com.example.grpc.TaskMessage.TaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.TaskMessage.TaskRequest other) {
        if (other == com.example.grpc.TaskMessage.TaskRequest.getDefaultInstance()) return this;
        if (!other.getPathPrefix().isEmpty()) {
          pathPrefix_ = other.pathPrefix_;
          onChanged();
        }
        if (!other.getPathSuffix().isEmpty()) {
          pathSuffix_ = other.pathSuffix_;
          onChanged();
        }
        if (other.getMaxNumber() != 0) {
          setMaxNumber(other.getMaxNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.TaskMessage.TaskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.TaskMessage.TaskRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pathPrefix_ = "";
      /**
       * <pre>
       * 路径前缀
       * </pre>
       *
       * <code>string pathPrefix = 1;</code>
       * @return The pathPrefix.
       */
      public java.lang.String getPathPrefix() {
        java.lang.Object ref = pathPrefix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pathPrefix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 路径前缀
       * </pre>
       *
       * <code>string pathPrefix = 1;</code>
       * @return The bytes for pathPrefix.
       */
      public com.google.protobuf.ByteString
          getPathPrefixBytes() {
        java.lang.Object ref = pathPrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pathPrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 路径前缀
       * </pre>
       *
       * <code>string pathPrefix = 1;</code>
       * @param value The pathPrefix to set.
       * @return This builder for chaining.
       */
      public Builder setPathPrefix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pathPrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 路径前缀
       * </pre>
       *
       * <code>string pathPrefix = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPathPrefix() {
        
        pathPrefix_ = getDefaultInstance().getPathPrefix();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 路径前缀
       * </pre>
       *
       * <code>string pathPrefix = 1;</code>
       * @param value The bytes for pathPrefix to set.
       * @return This builder for chaining.
       */
      public Builder setPathPrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pathPrefix_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pathSuffix_ = "";
      /**
       * <pre>
       * 路径后缀
       * </pre>
       *
       * <code>string pathSuffix = 2;</code>
       * @return The pathSuffix.
       */
      public java.lang.String getPathSuffix() {
        java.lang.Object ref = pathSuffix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pathSuffix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 路径后缀
       * </pre>
       *
       * <code>string pathSuffix = 2;</code>
       * @return The bytes for pathSuffix.
       */
      public com.google.protobuf.ByteString
          getPathSuffixBytes() {
        java.lang.Object ref = pathSuffix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pathSuffix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 路径后缀
       * </pre>
       *
       * <code>string pathSuffix = 2;</code>
       * @param value The pathSuffix to set.
       * @return This builder for chaining.
       */
      public Builder setPathSuffix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pathSuffix_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 路径后缀
       * </pre>
       *
       * <code>string pathSuffix = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPathSuffix() {
        
        pathSuffix_ = getDefaultInstance().getPathSuffix();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 路径后缀
       * </pre>
       *
       * <code>string pathSuffix = 2;</code>
       * @param value The bytes for pathSuffix to set.
       * @return This builder for chaining.
       */
      public Builder setPathSuffixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pathSuffix_ = value;
        onChanged();
        return this;
      }

      private int maxNumber_ ;
      /**
       * <pre>
       * 需要处理的最大编号
       * </pre>
       *
       * <code>int32 maxNumber = 3;</code>
       * @return The maxNumber.
       */
      @java.lang.Override
      public int getMaxNumber() {
        return maxNumber_;
      }
      /**
       * <pre>
       * 需要处理的最大编号
       * </pre>
       *
       * <code>int32 maxNumber = 3;</code>
       * @param value The maxNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMaxNumber(int value) {
        
        maxNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要处理的最大编号
       * </pre>
       *
       * <code>int32 maxNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxNumber() {
        
        maxNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:task.TaskRequest)
    }

    // @@protoc_insertion_point(class_scope:task.TaskRequest)
    private static final com.example.grpc.TaskMessage.TaskRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.TaskMessage.TaskRequest();
    }

    public static com.example.grpc.TaskMessage.TaskRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskRequest>
        PARSER = new com.google.protobuf.AbstractParser<TaskRequest>() {
      @java.lang.Override
      public TaskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.TaskMessage.TaskRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:task.TaskResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    java.util.List<com.example.grpc.TaskMessage.TaskResult> 
        getResultsList();
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    com.example.grpc.TaskMessage.TaskResult getResults(int index);
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    java.util.List<? extends com.example.grpc.TaskMessage.TaskResultOrBuilder> 
        getResultsOrBuilderList();
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    com.example.grpc.TaskMessage.TaskResultOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code task.TaskResponse}
   */
  public static final class TaskResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:task.TaskResponse)
      TaskResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResponse.newBuilder() to construct.
    private TaskResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResponse() {
      results_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                results_ = new java.util.ArrayList<com.example.grpc.TaskMessage.TaskResult>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(
                  input.readMessage(com.example.grpc.TaskMessage.TaskResult.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.TaskMessage.TaskResponse.class, com.example.grpc.TaskMessage.TaskResponse.Builder.class);
    }

    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<com.example.grpc.TaskMessage.TaskResult> results_;
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.grpc.TaskMessage.TaskResult> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.grpc.TaskMessage.TaskResultOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    @java.lang.Override
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    @java.lang.Override
    public com.example.grpc.TaskMessage.TaskResult getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .task.TaskResult results = 1;</code>
     */
    @java.lang.Override
    public com.example.grpc.TaskMessage.TaskResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.TaskMessage.TaskResponse)) {
        return super.equals(obj);
      }
      com.example.grpc.TaskMessage.TaskResponse other = (com.example.grpc.TaskMessage.TaskResponse) obj;

      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.TaskMessage.TaskResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code task.TaskResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:task.TaskResponse)
        com.example.grpc.TaskMessage.TaskResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.TaskMessage.TaskResponse.class, com.example.grpc.TaskMessage.TaskResponse.Builder.class);
      }

      // Construct using com.example.grpc.TaskMessage.TaskResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResponse_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResponse getDefaultInstanceForType() {
        return com.example.grpc.TaskMessage.TaskResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResponse build() {
        com.example.grpc.TaskMessage.TaskResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResponse buildPartial() {
        com.example.grpc.TaskMessage.TaskResponse result = new com.example.grpc.TaskMessage.TaskResponse(this);
        int from_bitField0_ = bitField0_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.TaskMessage.TaskResponse) {
          return mergeFrom((com.example.grpc.TaskMessage.TaskResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.TaskMessage.TaskResponse other) {
        if (other == com.example.grpc.TaskMessage.TaskResponse.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.TaskMessage.TaskResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.TaskMessage.TaskResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.grpc.TaskMessage.TaskResult> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          results_ = new java.util.ArrayList<com.example.grpc.TaskMessage.TaskResult>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.grpc.TaskMessage.TaskResult, com.example.grpc.TaskMessage.TaskResult.Builder, com.example.grpc.TaskMessage.TaskResultOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public java.util.List<com.example.grpc.TaskMessage.TaskResult> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public com.example.grpc.TaskMessage.TaskResult getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder setResults(
          int index, com.example.grpc.TaskMessage.TaskResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder setResults(
          int index, com.example.grpc.TaskMessage.TaskResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder addResults(com.example.grpc.TaskMessage.TaskResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder addResults(
          int index, com.example.grpc.TaskMessage.TaskResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder addResults(
          com.example.grpc.TaskMessage.TaskResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder addResults(
          int index, com.example.grpc.TaskMessage.TaskResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends com.example.grpc.TaskMessage.TaskResult> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public com.example.grpc.TaskMessage.TaskResult.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public com.example.grpc.TaskMessage.TaskResultOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public java.util.List<? extends com.example.grpc.TaskMessage.TaskResultOrBuilder> 
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public com.example.grpc.TaskMessage.TaskResult.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            com.example.grpc.TaskMessage.TaskResult.getDefaultInstance());
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public com.example.grpc.TaskMessage.TaskResult.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, com.example.grpc.TaskMessage.TaskResult.getDefaultInstance());
      }
      /**
       * <code>repeated .task.TaskResult results = 1;</code>
       */
      public java.util.List<com.example.grpc.TaskMessage.TaskResult.Builder> 
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.grpc.TaskMessage.TaskResult, com.example.grpc.TaskMessage.TaskResult.Builder, com.example.grpc.TaskMessage.TaskResultOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.grpc.TaskMessage.TaskResult, com.example.grpc.TaskMessage.TaskResult.Builder, com.example.grpc.TaskMessage.TaskResultOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:task.TaskResponse)
    }

    // @@protoc_insertion_point(class_scope:task.TaskResponse)
    private static final com.example.grpc.TaskMessage.TaskResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.TaskMessage.TaskResponse();
    }

    public static com.example.grpc.TaskMessage.TaskResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResponse>
        PARSER = new com.google.protobuf.AbstractParser<TaskResponse>() {
      @java.lang.Override
      public TaskResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.TaskMessage.TaskResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:task.TaskResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    boolean containsResult(
        java.lang.String key);
    /**
     * Use {@link #getResultMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getResult();
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getResultMap();
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */

    int getResultOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */

    int getResultOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code task.TaskResult}
   */
  public static final class TaskResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:task.TaskResult)
      TaskResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResult.newBuilder() to construct.
    private TaskResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                result_ = com.google.protobuf.MapField.newMapField(
                    ResultDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              result__ = input.readMessage(
                  ResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              result_.getMutableMap().put(
                  result__.getKey(), result__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskResult_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetResult();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.TaskMessage.internal_static_task_TaskResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.TaskMessage.TaskResult.class, com.example.grpc.TaskMessage.TaskResult.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private static final class ResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.example.grpc.TaskMessage.internal_static_task_TaskResult_ResultEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> result_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetResult() {
      if (result_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultDefaultEntryHolder.defaultEntry);
      }
      return result_;
    }

    public int getResultCount() {
      return internalGetResult().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */

    @java.lang.Override
    public boolean containsResult(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getResult() {
      return getResultMap();
    }
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Integer> getResultMap() {
      return internalGetResult().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    @java.lang.Override

    public int getResultOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; result = 1;</code>
     */
    @java.lang.Override

    public int getResultOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetResult().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetResult(),
          ResultDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        result__ = ResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, result__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.TaskMessage.TaskResult)) {
        return super.equals(obj);
      }
      com.example.grpc.TaskMessage.TaskResult other = (com.example.grpc.TaskMessage.TaskResult) obj;

      if (!internalGetResult().equals(
          other.internalGetResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetResult().getMap().isEmpty()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.TaskMessage.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.TaskMessage.TaskResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code task.TaskResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:task.TaskResult)
        com.example.grpc.TaskMessage.TaskResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResult_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.TaskMessage.TaskResult.class, com.example.grpc.TaskMessage.TaskResult.Builder.class);
      }

      // Construct using com.example.grpc.TaskMessage.TaskResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableResult().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.TaskMessage.internal_static_task_TaskResult_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResult getDefaultInstanceForType() {
        return com.example.grpc.TaskMessage.TaskResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResult build() {
        com.example.grpc.TaskMessage.TaskResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.TaskMessage.TaskResult buildPartial() {
        com.example.grpc.TaskMessage.TaskResult result = new com.example.grpc.TaskMessage.TaskResult(this);
        int from_bitField0_ = bitField0_;
        result.result_ = internalGetResult();
        result.result_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.TaskMessage.TaskResult) {
          return mergeFrom((com.example.grpc.TaskMessage.TaskResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.TaskMessage.TaskResult other) {
        if (other == com.example.grpc.TaskMessage.TaskResult.getDefaultInstance()) return this;
        internalGetMutableResult().mergeFrom(
            other.internalGetResult());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.TaskMessage.TaskResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.TaskMessage.TaskResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> result_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetResult() {
        if (result_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        return result_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableResult() {
        onChanged();;
        if (result_ == null) {
          result_ = com.google.protobuf.MapField.newMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        if (!result_.isMutable()) {
          result_ = result_.copy();
        }
        return result_;
      }

      public int getResultCount() {
        return internalGetResult().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */

      @java.lang.Override
      public boolean containsResult(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResultMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getResult() {
        return getResultMap();
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.Integer> getResultMap() {
        return internalGetResult().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */
      @java.lang.Override

      public int getResultOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */
      @java.lang.Override

      public int getResultOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetResult().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearResult() {
        internalGetMutableResult().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */

      public Builder removeResult(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableResult().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableResult() {
        return internalGetMutableResult().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */
      public Builder putResult(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableResult().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; result = 1;</code>
       */

      public Builder putAllResult(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableResult().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:task.TaskResult)
    }

    // @@protoc_insertion_point(class_scope:task.TaskResult)
    private static final com.example.grpc.TaskMessage.TaskResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.TaskMessage.TaskResult();
    }

    public static com.example.grpc.TaskMessage.TaskResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResult>
        PARSER = new com.google.protobuf.AbstractParser<TaskResult>() {
      @java.lang.Override
      public TaskResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.TaskMessage.TaskResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_TaskRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_TaskRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_TaskResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_TaskResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_TaskResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_TaskResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_task_TaskResult_ResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_task_TaskResult_ResultEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntask.proto\022\004task\"H\n\013TaskRequest\022\022\n\npat" +
      "hPrefix\030\001 \001(\t\022\022\n\npathSuffix\030\002 \001(\t\022\021\n\tmax" +
      "Number\030\003 \001(\005\"1\n\014TaskResponse\022!\n\007results\030" +
      "\001 \003(\0132\020.task.TaskResult\"i\n\nTaskResult\022,\n" +
      "\006result\030\001 \003(\0132\034.task.TaskResult.ResultEn" +
      "try\032-\n\013ResultEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\005:\0028\0012F\n\013TaskService\0227\n\014processTask" +
      "s\022\021.task.TaskRequest\032\022.task.TaskResponse" +
      "\"\000B!\n\020com.example.grpcB\013TaskMessageP\000b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_task_TaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_task_TaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_TaskRequest_descriptor,
        new java.lang.String[] { "PathPrefix", "PathSuffix", "MaxNumber", });
    internal_static_task_TaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_task_TaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_TaskResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_task_TaskResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_task_TaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_TaskResult_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_task_TaskResult_ResultEntry_descriptor =
      internal_static_task_TaskResult_descriptor.getNestedTypes().get(0);
    internal_static_task_TaskResult_ResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_task_TaskResult_ResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
